server:
  port: 80
eureka:
  client:
    register-with-eureka: false #向eureka注册中心注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.localhost3:7002/eureka/,http://eureka.localhost3:7002/eureka/,http://eureka.localhost2:7002/eureka/   #注册地址
spring:
  application:
    name: cloud-order-service